version: '2'

services:
  nginx:
    restart: always
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/src/static
  server:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/backend/server-entrypoint.sh
    volumes:
      - static_volume:/app/src/static
    expose:
      - 8000
    env_file:
      - ./src/chargik/.env
    # environment:
    #         DEBUG: "True"
    #         CELERY_BROKER_URL: "redis://redis:6379/0"
    #         CELERY_RESULT_BACKEND: "redis://redis:6379/0"
    #         DJANGO_DB: postgresql
    #         POSTGRES_HOST: db
    #         POSTGRES_NAME: postgres
    #         POSTGRES_USER: postgres
    #         POSTGRES_PASSWORD: postgres
    #         POSTGRES_PORT: 5432
  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/backend/celery-entrypoint.sh
    volumes:
      - static_volume:/app/src/static
    env_file:
      - ./src/chargik/.env
    depends_on:
      - server
      - redis
  redis:
    restart: unless-stopped
    image: redis
    expose:
      - 6379
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./src/chargik/.env
    expose:
      - 5432
volumes:
  static_volume: {}
  postgres_data: {}