FROM python:3.11

COPY ./src/ /app/
WORKDIR /app

# os-level installs# os-level installs
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    python3-dev \
    python3-setuptools \
    libpq-dev \
    gcc \
    make \
    redis

# venv installs
RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/python -m pip install pip --upgrade \
    /opt/venv/bin/python -m pip install -r /app/requirements.txt


# purge unused
RUN apt-get remove -y --purge make gcc build-essential \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
RUN apt-get update

RUN chmod +x ./config/entrypoint.sh

CMD ["./config/entrypoint.sh"]

# RUN python -m celery -A chargik worker