# Generated by Django 4.2 on 2023-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, default="", verbose_name="Номер счета"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Подтверждена", "Подтверждена"),
                            ("В обработке", "В обработке"),
                            ("Отменена", "Отменена"),
                        ],
                        default="В обработке",
                        max_length=20,
                    ),
                ),
                ("paid", models.BooleanField(default=False, verbose_name="Оплачен?")),
                (
                    "tourists_qouta_adult",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество взрослых"
                    ),
                ),
                (
                    "tourists_qouta_child",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Количество детей"
                    ),
                ),
                (
                    "ammount_total",
                    models.FloatField(blank=True, null=True, verbose_name="Итого"),
                ),
                (
                    "comission",
                    models.FloatField(blank=True, null=True, verbose_name="Комиссия"),
                ),
                (
                    "ammount_to_pay",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Итого к оплате"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Счёт",
                "verbose_name_plural": "Счета",
                "ordering": ["-timestamp", "-updated"],
            },
        ),
    ]
