# Generated by Django 4.2 on 2023-10-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tours", "0001_initial"),
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="dates",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tours.tourdayquota",
                verbose_name="Даты тура",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tours.tour",
                verbose_name="Название тура",
            ),
        ),
    ]
