# Generated by Django 4.2 on 2023-09-09 05:31

import ckeditor_uploader.fields
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0002_alter_tour_options_tour_active_tour_comission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="img",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to="tours_img_upload",
            ),
        ),
        migrations.AlterField(
            model_name="tourdescriptionday",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
