# Generated by Django 4.2 on 2023-09-09 05:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0004_alter_tourdescriptionday_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourdescriptionday",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
