# Generated by Django 4.2 on 2023-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0005_alter_tourdescriptionday_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Ссылка на тур"),
        ),
    ]
