# Generated by Django 4.2 on 2023-09-12 15:59

from django.db import migrations, models
import django_resized.forms
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0006_alter_tour_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="count_views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tour",
            name="img",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1920, 1080],
                upload_to=tours.models.tours_img_upload,
            ),
        ),
    ]
