# Generated by Django 4.2 on 2023-09-23 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import tours.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tours", "0008_tourdayquota"),
    ]

    operations = [
        migrations.AddField(
            model_name="tour",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="img",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=75,
                scale=None,
                size=[1024, 768],
                upload_to=tours.models.tours_img_upload,
            ),
        ),
        migrations.AlterField(
            model_name="tourdayquota",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Активная дата"),
        ),
    ]
