# Generated by Django 4.2 on 2023-09-25 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0009_tour_user_alter_tour_img_alter_tourdayquota_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="not_included",
            field=models.TextField(
                blank=True, null=True, verbose_name="Дополнительно оплачивается"
            ),
        ),
        migrations.AlterField(
            model_name="tourdescriptionday",
            name="tour",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tours.tour",
                verbose_name="Тур",
            ),
        ),
    ]
