# Generated by Django 4.2 on 2023-09-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0010_alter_tour_not_included_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Тип тура",
                "verbose_name_plural": "Типы туров",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="CountryTour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=128)),
                ("slug", models.SlugField(unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Страна",
                "verbose_name_plural": "Страны",
                "ordering": ["title"],
            },
        ),
        migrations.RemoveField(
            model_name="tour",
            name="country",
        ),
        migrations.AddField(
            model_name="tour",
            name="category",
            field=models.ManyToManyField(to="tours.categorytour"),
        ),
        migrations.AddField(
            model_name="tour",
            name="country",
            field=models.ManyToManyField(to="tours.countrytour"),
        ),
    ]
