# Generated by Django 4.2 on 2023-10-25 07:43

import ckeditor_uploader.fields
from django.db import migrations, models
import django_resized.forms
import hotels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "title",
                    models.CharField(
                        default="", max_length=255, verbose_name="Название отеля"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Ссылка на отель")),
                (
                    "img",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[1024, 768],
                        upload_to=hotels.models.hotels_img_upload,
                    ),
                ),
                (
                    "price_from",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Стоимость от",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("$", "$"), ("€", "€"), ("BYN", "BYN"), ("₽", "₽")],
                        default="BYN",
                        max_length=10,
                        verbose_name="валюта",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True, verbose_name="Описание отеля"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Опубликовано"
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Время изменения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Отель",
                "verbose_name_plural": "Отели",
                "ordering": ["-timestamp", "-updated"],
            },
        ),
    ]
