# Generated by Django 4.2 on 2023-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CallBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="", max_length=40, verbose_name="Как вас зовут?"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        default="", max_length=15, verbose_name="Ваш номер телефона"
                    ),
                ),
                ("url", models.URLField(default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-timestamp"],
            },
        ),
    ]
