# Generated by Django 4.2 on 2023-10-02 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("callback", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="callback",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
            },
        ),
    ]
